use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Resolve the crate directory containing this build script. When unavailable
    // (e.g., editor background tasks), fall back to current_dir and avoid panics.
    let manifest_dir = match env::var("CARGO_MANIFEST_DIR") {
        Ok(val) => PathBuf::from(val),
        Err(_) => match env::current_dir() {
            Ok(p) => p,
            Err(_) => return, // best-effort: skip generation gracefully
        },
    };
    let styles_dir = manifest_dir.join("styles");
    println!("cargo:rerun-if-changed={}", styles_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries = Vec::new();
    if let Ok(rd) = fs::read_dir(&styles_dir) {
        for ent in rd.flatten() {
            let path = ent.path();
            if let Some(ext) = path.extension()
                && (ext == "yaml" || ext == "yml")
            {
                let name = path
                    .file_stem()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string();
                let rel_inner = match path.strip_prefix(&manifest_dir) {
                    Ok(p) => p.to_string_lossy().to_string(),
                    Err(_) => path.to_string_lossy().to_string(),
                };
                let rel = format!("../{rel_inner}");
                entries.push((name, rel));
            }
        }
    }
    entries.sort();

    let out_path = manifest_dir.join("src/styles_gen.rs");
    let mut code = String::new();
    code.push_str("// @generated by build.rs\n");
    code.push_str("pub static STYLE_REGISTRY: &[(&str, &str)] = &[\n");
    for (name, rel) in entries {
        let line = format!("    (\"{name}\", include_str!(\"{rel}\")),\n");
        code.push_str(&line);
    }

    // Close array properly with semicolon and trailing newline.
    code.push_str("];\n");
    if let Err(e) = fs::write(out_path, code) {
        println!("cargo:warning=failed to write styles_gen.rs: {e}");
    }
}
