use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let styles_dir = manifest_dir.join("styles");
    println!("cargo:rerun-if-changed={}", styles_dir.display());

    let mut entries = Vec::new();
    if let Ok(rd) = fs::read_dir(&styles_dir) {
        for ent in rd.flatten() {
            let path = ent.path();
            if let Some(ext) = path.extension() {
                if ext == "yaml" || ext == "yml" {
                    let name = path
                        .file_stem()
                        .unwrap_or_default()
                        .to_string_lossy()
                        .to_string();
                    let rel = format!(
                        "../{}",
                        path.strip_prefix(&manifest_dir).unwrap().to_string_lossy()
                    );
                    entries.push((name, rel));
                }
            }
        }
    }
    entries.sort();

    let out_path = manifest_dir.join("src/styles_gen.rs");
    let mut code = String::new();
    code.push_str(
        "// @generated by build.rs
",
    );
    code.push_str(
        "pub static STYLE_REGISTRY: &[(&str, &str)] = &[
",
    );
    for (name, rel) in entries {
        let line = format!("    (\"{}\", include_str!(\"{}\")),\n", name, rel);
        code.push_str(&line);
    }

    code.push_str("];");
    fs::write(out_path, code).unwrap();
}
