// @generated by build.rs
pub static STYLE_REGISTRY: &[(&str, &str)] = &[
    ("checklist", include_str!("../styles/checklist.yaml")),
    ("explanatory", include_str!("../styles/explanatory.yaml")),
    ("learning", include_str!("../styles/learning.yaml")),
    ("verbose", include_str!("../styles/verbose.yaml")),
];